name: linting, testing, building
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: build production project
        if: always()
        run: npm run build:prod
      - name: linting typescript
        if: always()
        run: npm run lint:ts
      - name: linting css
        if: always()
        run: npm run lint:scss
      - name: unit testing
        if: always()
        run: npm run test:unit
      - name: build storybook
        if: always()
        run: npm run storybook:build
    - name: loki test screenshot
        run: npm run test:ui:ci
        if: always()
      - name: make report
        run: npm run test:ui:report
        if: failure()
      - name: save report
        uses: actions/upload-artifact@v3
        with:
          name: 'loki difference ${{ github.run_number }}'
          path: .loki/
          retention-days: 2
        if: failure()

   
